/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diordiouf;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Dior
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        symetrique = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hachage = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        asymetrique = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        signature = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(236, 242, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(29, 190, 195));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diordiouf/images/icons8-clés-2-64.png"))); // NOI18N
        jLabel12.setText("jLabel12");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Bienvenue Dans Votre Application TDSI Secure");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TDSI Secure");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jLabel13)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 120));

        symetrique.setBackground(java.awt.SystemColor.controlHighlight);
        symetrique.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                symetriqueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                symetriqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                symetriqueMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diordiouf/images/icons8-symmetric-encryption-66 (2).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(29, 190, 195));
        jLabel2.setText(" Symétrique");

        javax.swing.GroupLayout symetriqueLayout = new javax.swing.GroupLayout(symetrique);
        symetrique.setLayout(symetriqueLayout);
        symetriqueLayout.setHorizontalGroup(
            symetriqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, symetriqueLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(symetriqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(symetriqueLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addGap(15, 15, 15))
        );
        symetriqueLayout.setVerticalGroup(
            symetriqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, symetriqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        jPanel1.add(symetrique, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 130, 100));

        jPanel4.setBackground(java.awt.SystemColor.controlHighlight);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diordiouf/images/icons8-asymmetrik-64.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(29, 190, 195));
        jLabel5.setText(" Asymétrique");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(14, 14, 14))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, 100));

        hachage.setBackground(java.awt.SystemColor.controlHighlight);
        hachage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hachageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hachageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hachageMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diordiouf/images/icons8-blockchain-transactions-64.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(29, 190, 195));
        jLabel7.setText("Hachage");

        javax.swing.GroupLayout hachageLayout = new javax.swing.GroupLayout(hachage);
        hachage.setLayout(hachageLayout);
        hachageLayout.setHorizontalGroup(
            hachageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hachageLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(hachageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21))
        );
        hachageLayout.setVerticalGroup(
            hachageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hachageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel1.add(hachage, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, 100));

        asymetrique.setBackground(java.awt.SystemColor.controlHighlight);
        asymetrique.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asymetriqueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                asymetriqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                asymetriqueMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diordiouf/images/icons8-asymmetrik-64.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(29, 190, 195));
        jLabel9.setText(" Asymétrique");

        javax.swing.GroupLayout asymetriqueLayout = new javax.swing.GroupLayout(asymetrique);
        asymetrique.setLayout(asymetriqueLayout);
        asymetriqueLayout.setHorizontalGroup(
            asymetriqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asymetriqueLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(asymetriqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asymetriqueLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asymetriqueLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(14, 14, 14))))
        );
        asymetriqueLayout.setVerticalGroup(
            asymetriqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asymetriqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(21, 21, 21))
        );

        jPanel1.add(asymetrique, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, 100));

        signature.setBackground(java.awt.SystemColor.controlHighlight);
        signature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signatureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signatureMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diordiouf/images/icons8-empreinte-100.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(29, 190, 195));
        jLabel11.setText("Signature");

        javax.swing.GroupLayout signatureLayout = new javax.swing.GroupLayout(signature);
        signature.setLayout(signatureLayout);
        signatureLayout.setHorizontalGroup(
            signatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signatureLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(signatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signatureLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signatureLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(14, 14, 14))))
        );
        signatureLayout.setVerticalGroup(
            signatureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signatureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(21, 21, 21))
        );

        jPanel1.add(signature, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(873, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void symetriqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_symetriqueMouseEntered
        // TODO add your handling code here:
        setColor(symetrique);
    }//GEN-LAST:event_symetriqueMouseEntered

    private void symetriqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_symetriqueMouseExited
        // TODO add your handling code here:
        resetColor(symetrique);
    }//GEN-LAST:event_symetriqueMouseExited

    private void asymetriqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asymetriqueMouseEntered
        // TODO add your handling code here:
        setColor(asymetrique);
    }//GEN-LAST:event_asymetriqueMouseEntered

    private void asymetriqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asymetriqueMouseExited
        // TODO add your handling code here:
        resetColor(asymetrique);
    }//GEN-LAST:event_asymetriqueMouseExited

    private void signatureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signatureMouseEntered
        // TODO add your handling code here:
        setColor(signature);
    }//GEN-LAST:event_signatureMouseEntered

    private void signatureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signatureMouseExited
        // TODO add your handling code here:
        resetColor(signature);
    }//GEN-LAST:event_signatureMouseExited

    private void hachageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hachageMouseEntered
        // TODO add your handling code here:
        setColor(hachage);
    }//GEN-LAST:event_hachageMouseEntered

    private void hachageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hachageMouseExited
        // TODO add your handling code here:
        resetColor(hachage);
    }//GEN-LAST:event_hachageMouseExited

    private void symetriqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_symetriqueMouseClicked
        // TODO add your handling code here:
        CipherSymetric jframe = new CipherSymetric();
        this.setVisible(false);
        jframe.setVisible(true);
        jframe.setResizable(false);
    }//GEN-LAST:event_symetriqueMouseClicked

    private void asymetriqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asymetriqueMouseClicked
        // TODO add your handling code here:
        
        AsymetriCipher asymetriCipher = new AsymetriCipher();
        this.setVisible(false);
        asymetriCipher.setVisible(true);
        asymetriCipher.setResizable(false);
    }//GEN-LAST:event_asymetriqueMouseClicked

    private void hachageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hachageMouseClicked
        // TODO add your handling code here:
        HachageFrame hachageFrame = new HachageFrame();
        this.setVisible(false);
        hachageFrame.setVisible(true);
        hachageFrame.setResizable(false);
    }//GEN-LAST:event_hachageMouseClicked
    public void setColor(JPanel panel){
        
        panel.setBackground(new java.awt.Color(153,153,153));
        
    }
    public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(204,204,204));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel asymetrique;
    private javax.swing.JPanel hachage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel signature;
    private javax.swing.JPanel symetrique;
    // End of variables declaration//GEN-END:variables
}
